#!/bin/ksh
# vim: noai:ts=4:sw=4:expandtab

# Copyright (C) 2019 tribe29 GmbH - License: GNU General Public License v2
# This file is part of Checkmk (https://checkmk.com). It is subject to the terms and
# conditions defined in the file COPYING, which is part of this source code package.

for haproxy_sock in /run/haproxy/admin.sock /var/lib/haproxy/stats; do
    if [ -r "${haproxy_sock}" ] && inpath socat; then
        mkecho "<<<haproxy:sep(44)>>>"
        mkecho "show stat" | socat - "UNIX-CONNECT:${haproxy_sock}"
    fi
done