#!/bin/ksh
# vim: noai:ts=4:sw=4:expandtab

# Copyright (C) 2019 tribe29 GmbH - License: GNU General Public License v2
# This file is part of Checkmk (https://checkmk.com). It is subject to the terms and
# conditions defined in the file COPYING, which is part of this source code package.

# Get statistics about monitored jobs. Below the job directory there
# is a sub directory per user that ran a job. That directory must be
# owned by the user so that a symlink or hardlink attack for reading
# arbitrary files can be avoided.
(
    cd "${MK_VARDIR}/job" || return
    mkecho '<<<job>>>'
    case "${MK_OSSTR}" in
        (aix)
            for _username in *; do
                if [ -d "${_username}" ] && cd "${_username}"; then
                    for _filename in *; do
                        # Maybe a cursory "if [ -r "${_filename}" ]" could go here?
                        mkecho "==> ${_filename} <=="
                        cat "${_filename}"
                    done
                    cd ..
                fi
            done
        ;;
        (linux)
            for _username in *; do
                if [ -d "${_username}" ] && cd "${_username}"; then
                    if [ "${EUID}" -eq 0 ]; then
                        su -s "${SHELL}" "${_username}" -c "head -n -0 -v *"
                    else
                        head -n -0 -v ./*
                    fi
                    cd ..
                fi
            done
        ;;
        (solaris)
            for _username in *; do
                if [ -d "${_username}" ] && cd "${_username}" ; then
                    _count=$(su -s "${SHELL}" "${_username}" -c "ls -1 * | wc -l")

                    if [ "${_count}" -eq "1" ]; then
                        _filename=$(su -s "${SHELL}" "${_username}" -c "ls -1 *")
                        mkecho "==> ${_filename} <=="
                    fi

                    su -s "${SHELL}" "${_username}" -c "head -n1000 *"
                    cd ..
                fi
            done
        ;;
    esac
)
unset -v _username _filename _count