#!/bin/ksh
# vim: noai:ts=4:sw=4:expandtab

# Copyright (C) 2019 tribe29 GmbH - License: GNU General Public License v2
# This file is part of Checkmk (https://checkmk.com). It is subject to the terms and
# conditions defined in the file COPYING, which is part of this source code package.

if inpath nvidia-settings && [ -S /tmp/.X11-unix/X0 ]; then
    mkecho '<<<nvidia>>>'
    for _var in GPUErrors GPUCoreTemp; do
        DISPLAY=:0 waitmax 2 nvidia-settings -t -q "${_var}" | sed "s/^/${_var}: /"
    done
    unset -v _var
fi