#!/bin/ksh
# vim: noai:ts=4:sw=4:expandtab

# Copyright (C) 2019 tribe29 GmbH - License: GNU General Public License v2
# This file is part of Checkmk (https://checkmk.com). It is subject to the terms and
# conditions defined in the file COPYING, which is part of this source code package.

[ "${MK_OSSTR}" = "solaris" ] || exit 1

if inpath prtdiag; then
    # prtdiag does not work in local zones
    if [ "${zonename}" = "global" ]; then
        run_cached_cmd solaris_prtdiag_status 300 '/usr/sbin/prtdiag 1>/dev/null 2>&1; mkecho $?'
    fi
fi

# Displaying Information About Faults or Defects
# If there are no faults the output of this command will be empty.
if inpath fmadm; then
    mkecho '<<<solaris_fmadm:sep(58)>>>'
    fmadm faulty
fi